version: "3.8"

services:
  psql-insurance:
    image: postgres
    container_name: psql-insurance
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payroll
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgres/sql/postgresql.conf

  recipe:
    container_name: employee_insurance
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-insurance:5432/payroll
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    links:
      -  psql-insurance